Donovan Griego
Lab 02
September 14, 2020

Script started on 2020-09-14 11:17:00-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="190" LINES="12"]
]0;dxgriego@Parallels: ~/cse113/lab2[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab2[00m$ exit./rock-spock gcc -g -Wall rock-spock.c -o rock-spock
]0;dxgriego@Parallels: ~/cse113/lab2[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab2[00m$ gcc -g -Wall rock-spock.c -o rock-spock
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexit[K./rock-spock 
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: R
Player's play is ROCK
Computer's play is ROCK
It's a tie! No Winner!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: P
Player's play is PAPER
Computer's play is ROCK
Paper covers rock. Player Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: V
Player's play is SPOCK
Computer's play is SPOCK
It's a tie! No Winner!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: V
Player's play is SPOCK
Computer's play is LIZARD
Lizard poisons spock. Computer Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: S
Player's play is SCISSORS
Computer's play is PAPER
Scissors cuts paper. Player Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: P
Player's play is PAPER
Computer's play is SCISSORS
Scissors cuts paper. Computer Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: P
Player's play is PAPER
Computer's play is SCISSORS
Scissors cuts paper. Computer Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: V
Player's play is SPOCK
Computer's play is SPOCK
It's a tie! No Winner!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: R
Player's play is ROCK
Computer's play is LIZARD
Rock crushes lizard. Player Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: L
Player's play is LIZARD
Computer's play is ROCK
Rock crushes lizard. Computer Wins!
Press enter to continue...
Enter a move:
R for ROCK
P for PAPER
S for SCISSORS
L for LIZARD
V for SPOCK
Q to have SPOCK eat a ROCK while chasing a LIZARD and quit
Move: Q
]0;dxgriego@Parallels: ~/cse113/lab2[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab2[00m$ exit
exit

Script done on 2020-09-14 11:18:32-06:00 [COMMAND_EXIT_CODE="0"]
